Fuling:
  Meadows:
    amount: 0
  Black Forest:
    amount: 0
  Swamp:
    amount: 0
  Mountain:
    amount: 0

Succubus:
  health: 2.0

TentaRoot:
  health: 3.0
  infusion:
    Frost: 100

Kraken:
  amount: 0
