Fuling:
  Meadows:
    amount: 0
  Black Forest:
    amount: 0
  Swamp:
    amount: 0
  Mountain:
    amount: 0

Succubus:
  health: 4.0

TentaRoot:
  health: 3.0
  damage: 2.0
  infusion:
    Frost: 100

Kraken:
  amount: 0

Succubus_Queen1:
  health: 2.0
  stars:
    0: default
    1: default
    2: default
    3: default
    4: default
    5: [17, 28, 38, 12, 5]
  effect:
    Armored

GoblinLoot:
  health: 10.0
  stars:
    0: default
    1: default
    2: default
    3: default
    4: default
    5: [17, 28, 38, 12, 5]
  effect:
    Quick
